# Logo
logo_image_source: /logo.svg

# Index Page
index_banner_text: C'est Schopenlaam
index_banner_text_secondary: Make devs easier
index_font_awesome_icon_css: fa fa-bath

# Header
menu:
  Home: /
  # Archives: /archives
  # Tags: /tags
  # Categories: /categories
  # About: /about.html
  # Contact: /contact.html
  B64: /b64
  Mouse Pro: /mouse-pro
  Private Vault: /private-vault
  Wukong Database: /wukong-db
  Privacy: /privacy

# Post
default_post_title: Untitled
default_post_icon: fa-lightbulb-o

# Archive Date Format
archive_date_format: MMM YYYY
archive_font_awesome_icon_css: fa-folder-open

# About Widget
about_widget_avatar_url: https://avatars.githubusercontent.com/u/169142455?s=40&v=4
about_widget_text: "Salut! Je m'appelle Schopenlaam."


# Comments.
comments:
  # Disqus comments
  disqus_shortname: 

# Google Analytics Tracking ID
google_analytics:

# Social Media Platforms
social_platforms:
  # - url: https://twitter.com/?lang=en
  #   fa_icon: fa-twitter
  # - url: https://www.facebook.com/
  #   fa_icon: fa-facebook
  # - url: https://dribbble.com/
  #   fa_icon: fa-dribbble 
  - url: https://github.com/schopenlaam
    fa_icon: fa-github
  # - url: https://plus.google.com/
  #   fa_icon: fa-google-plus
  # - url: https://www.behance.net/
  #   fa_icon: fa-behance
  # - url: https://500px.com/
  #   fa_icon: fa-500px
  # - url: mailto:test@example.com
  #   fa_icon: fa-envelope
  # - url: /#
  #   fa_icon: fa-rss

# Footer about
footer_about: "Schopenlaam 2024 All right reserved."
